name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Debug - List workspace contents
        run: ls -la

      - name: Debug - Show current directory
        run: pwd

      - name: Debug - List project structure
        run: find . -type f -name "*.py" -o -name "*.html" -o -name "*.js" -o -name "requirements.txt" | head -20

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        
      - name: Install dependencies
        run: |
          if [ -f api/requirements.txt ]; then
            pip install -r api/requirements.txt
          else
            echo "No requirements.txt found in api directory"
          fi
        
      - name: Verify API Token exists
        run: |
          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
            echo "ERROR: AZURE_STATIC_WEB_APPS_API_TOKEN secret is not set"
            exit 1
          fi
          echo "API Token is set (length: ${#AZURE_STATIC_WEB_APPS_API_TOKEN})"
        env:
          AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "./static"
          api_location: "./api" 
          output_location: ""
          skip_app_build: false
          skip_api_build: false
          api_build_command: "python -m pip install --upgrade pip && pip install -r requirements.txt"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: close